import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/Theme-provider";

import {ClerkProvider} from "@clerk/nextjs"
import {dark } from "@clerk/themes"


const inter = Inter({subsets: ["latin"]});
export const metadata: Metadata = {
  title: "JobPrepper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
        <ThemeProvider
            attribute="class"
            enableSystem
            defaultTheme="system"
            disableTransitionOnChange
          >
            
            <main className="min-h-screen">
              {children}
            </main>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
